### ISSUE TITLE
ftp.freetds.org is down

### ISSUE THREAD

**Issue by divinpaul** [FreeTDS/freetds#364] opened 2020-10-19 06:00 UTC
Hey team,

It seems like `ftp.freetds.org` is down.

```
curl ftp://ftp.freetds.org/pub/freetds/stable/freetds-0.91.tar.gz                                                                                                                                     
curl: (6) Could not resolve host: ftp.freetds.org
```
I'm not sure if anyone else is facing this issue?

**Comment by freddy77** [comment] 2020-10-19 08:36
Checking, thanks

**Comment by freddy77** [comment] 2020-10-19 08:37
Duplicate of #363

**Closed by freddy77** 2020-10-19 08:37 UTC
