### ISSUE TITLE
brew install freetds --with-unixodbc fails erroring out invalid option: --with-unixodbc

### ISSUE THREAD

**Issue by raagha-b** [FreeTDS/freetds#257] opened 2019-02-13 09:27 UTC
brew install freetds --with-unixodbc is failing with mac 10.14 versions.
Error: invalid option: --with-unixodbc
Return status: 1

**Comment by freddy77** [comment] 2019-02-13 10:12
I do not maintain brew packages, you should contact brew maintainer.

**Comment by reganoneill** [comment] 2019-02-13 23:38
I am also experiencing this same issue (mac 10.14)
Difficult to understand why support for these options was yanked.

**Comment by davidjb** [comment] 2019-02-14 06:00
The `--with-unixodbc` option is no longer required because it's now configured by default (https://github.com/Homebrew/homebrew-core/blob/master/Formula/freetds.rb#L32) so just do:

```
brew install freetds
```

and that's done.  For note, Homebrew removed options across all formulae, not just FreeTDS (https://github.com/Homebrew/homebrew-core/issues/31510). 

In any case, this issue is definitely unrelated to here, the upstream project.

**Comment by raagha-b** [comment] 2019-02-14 07:28
@davidjb --with-unixodbc used to take care of installing odbc driver.
Kindly confirm whether that is take care by default ?

**Comment by davidjb** [comment] 2019-02-14 12:15
@raagha-b Yes it does. As linked above, the `--with-unixodbc`` option is now enabled for the formula, plus I can confirm it because I've installed it and and the ODBC driver is provided.  Here's the commit which enacted the change:  https://github.com/Homebrew/homebrew-core/commit/f3664604cbde0ab135e7af48c8e6db0b72b7f5d3#diff-36e24d7f2ca71867d98f2d1503ad6f14

@freddy77  This can be closed as resolved / relating to a different project

**Comment by freddy77** [comment] 2019-02-14 14:16
Closed as referring to a different project.

**Closed by freddy77** 2019-02-14 14:16 UTC
