### ISSUE TITLE
Mac OS crash (was: TLS 1.2 support for MS SQL Server)

### ISSUE THREAD

**Issue by CaptainDaVinci** [FreeTDS/freetds#387] opened 2021-03-03 04:22 UTC
Hi, I have a question, does freetds support TLS 1.2 for MS SQL Server? 
We are using FreeTDS currently on Ubuntu 18.04 and recently the MS SQL Server has been updated to TLS 1.2 and would like to know if we can configure FreeTDS to use TLS 1.2 as well. 

Thank you!

**Comment by freddy77** [comment] 2021-03-06 20:26
Il giorno mer 3 mar 2021 alle ore 04:22 Yash Kothari <
notifications@github.com> ha scritto:

> Hi, I have a question, does freetds support TLS 1.2 for MS SQL Server?
> We are using FreeTDS currently on Ubuntu 18.04 and recently the MS SQL
> Server has been updated to TLS 1.2 and would like to know if we can
> configure FreeTDS to use TLS 1.2 as well.
>
> Thank you!
>
Hi,
  personally I would be wondering: "Is there a way to disable TLS 1.1?"
There's an option to disable 1.0 but not to disable 1.1.
I think both OpenSSL and GnuTLS today support TLS 1.3.

Regards,
  Frediano

**Comment by CaptainDaVinci** [comment] 2021-03-07 05:44
Thanks @freddy77 , so if I understand correctly - FreeTDS wit GnuTLS should be able to connect to MS SQL Server TLS 1.2?

**Comment by yllus** [comment] 2021-03-29 16:18
Hi there - to add to this, on Mac OS X (Big Sur, v.11.2.3), I believe there is currently a crash being caused when FreeTDS is used with a TDS version above 7.0 (7.1, 7.2, 7.3 and 7.4 cause a crash; 7.0 is fine), and I suspect the cause is that version 7.1 and above attempt to call `tds_ssl_init`, which calls `TLSv1_2_enc_data` and immediately fails. Perhaps this is because I installed FreeTDS via the `brew` command, which links to OpenSSL 1.1 ( https://formulae.brew.sh/formula/freetds )?

The crash report I get from OS X reads:

`Process:               php-cgi [83379]
Path:                  /Applications/MAMP/*/php-cgi
Identifier:            php-cgi
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        php-cgi [83341]
Responsible:           MAMP PRO [57475]
User ID:               501

Date/Time:             2021-03-29 12:00:41.420 -0400
OS Version:            macOS 11.2.3 (20D91)
Report Version:        12
Anonymous UUID:        A1493A0E-0B1F-0AC5-11B0-5D1F31FAB75C

Sleep/Wake UUID:       31361574-DC93-47F4-9444-A0EC8A76481B

Time Awake Since Boot: 1200000 seconds
Time Since Wake:       10000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x0000000108bbc7a0
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Bus error: 10
Termination Reason:    Namespace SIGNAL, Code 0xa
Terminating Process:   exc handler [83379]

VM Regions Near 0x108bbc7a0:
    __TEXT                      108b65000-108bb5000    [  320K] r-x/rwx SM=COW  /usr/local/Cellar/openssl@1.1/1.1.1k/lib/libssl.1.1.dylib
--> __DATA_CONST                108bb5000-108bbd000    [   32K] r--/rwx SM=COW  /usr/local/Cellar/openssl@1.1/1.1.1k/lib/libssl.1.1.dylib
    __DATA                      108bbd000-108bc5000    [   32K] rw-/rwx SM=COW  /usr/local/Cellar/openssl@1.1/1.1.1k/lib/libssl.1.1.dylib

Application Specific Information:
crashed on child side of fork pre-exec
*** multi-threaded process forked ***

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   ???                                 0x0000000108bbc7a0 TLSv1_2_enc_data + 0
1   libtdsodbc.so                       0x0000000108b385db tds_ssl_init + 276
2   libtdsodbc.so                       0x0000000108b22959 tds_connect + 3726
3   libtdsodbc.so                       0x0000000108b21ac5 tds_connect_and_login + 23
4   libtdsodbc.so                       0x0000000108b0f00d odbc_connect + 301
5   libtdsodbc.so                       0x0000000108b09bfd _SQLDriverConnect + 461
6   libtdsodbc.so                       0x0000000108b09d19 SQLDriverConnect + 88
7   libodbc.2.dylib                     0x0000000108a10a23 SQLDriverConnect + 3128
8   pdo_odbc.so                         0x00000001087dacca pdo_odbc_handle_factory + 762 (odbc_driver.c:455)`

**Comment by freddy77** [comment] 2021-05-16 15:47
@yllus not much related the Mac problem. Are you sure you don't have 2 OpenSSL library versions and you compiled with some headers and using the another OpenSSL library?

**Comment by yllus** [comment] 2021-05-17 02:00
> @yllus not much related the Mac problem. Are you sure you don't have 2 OpenSSL library versions and you compiled with some headers and using the another OpenSSL library?

You are absolutely correct; I've deleted my message, sorry if it wasted your time! You are a king amongst men for the work you do here. :)

**Comment by freddy77** [comment] 2022-01-15 17:54
Closing.

**Closed by freddy77** 2022-01-15 17:54 UTC
