### ISSUE TITLE
TDS Version version higher than 5 is slow

### ISSUE THREAD

**Issue by wecode-apps** [FreeTDS/freetds#401] opened 2021-06-12 08:49 UTC
hey,
it is normal for TDS_Version 5 to load a questy in 5 seconds and with any version higher takes about 120 second ?
also when i use version 5 column name gets truncated to 30 characters ...
Thanks

**Comment by freddy77** [comment] 2021-06-12 10:01
Il giorno sab 12 giu 2021 alle ore 09:49 wecode-apps <
***@***.***> ha scritto:

> hey,
> it is normal for TDS_Version 5 to load a questy in 5 seconds and with any
> version higher takes about 120 second ?
> Thanks
>
Hi,
   version 5 is for Sybase, higher for MSSQL so either one of them should
fail.
Usually queries take very little time, in order of milliseconds, not
seconds so you are probably doing something wrong.

Regards,
  Frediano

**Comment by wecode-apps** [comment] 2021-06-12 10:02
can i hire you to do this debug ?

**Comment by fziglio** [comment] 2021-06-17 05:29
I'm pretty busy at the moment. But if the issue is so visible probably it won't be difficult to remove. Did you do some base tests? Like https://www.freetds.org/userguide/serverthere.html. Please post your system details (like OS, version and so on) and your configuration (like `freetds.conf` detail, `odbc.ini` and such).

**Comment by freddy77** [comment] 2022-01-15 17:56
No reply for more than a year, closing.

**Closed by freddy77** 2022-01-15 17:56 UTC
