### ISSUE TITLE
FreeTDS Pool low performance 

### ISSUE THREAD

**Issue by misterion** [FreeTDS/freetds#40] opened 2015-12-16 11:10 UTC
You can abserve that FreeTDS Pool works well (from master) but still has very very low perfomance(using [this one line test](https://gist.github.com/misterion/85c5d6cb32e4ddd487ce) ).
The connection speed with freetds as is would be very low ~2,8ms per connnection. If launch same test with tdspool ~446ms per connection. 

The query results with [query test](https://gist.github.com/misterion/c0cb0d12fc5d246740e1) is same. Approximately 1ms per query `SELECT 1,2,3` and ~1253 ms in case of pool using.

**Comment by freddy77** [comment] 2015-12-16 11:27
Yes, is a problem of socket settings causing some delays (or at least I hope the problem is the same). Got some patches to fix these issues.

**Comment by freddy77** [comment] 2015-12-16 11:39
Can you try this branch? https://github.com/freddy77/freetds/tree/slow_pool

**Comment by misterion** [comment] 2015-12-16 11:58
Sure. Now I compile and tell you the results.

**Comment by misterion** [comment] 2015-12-16 12:04
Freed are you shure is actualy works ?
```
tsql.c: In function ‘do_query’:
tsql.c:91: error: ‘TDSCOLINFO’ has no member named ‘column_textsize’
tsql.c:94: error: ‘TDSCOLINFO’ has no member named ‘cur_row_size’
tsql.c: In function ‘main’:
tsql.c:267: warning: passing argument 1 of ‘tds_connect’ from incompatible pointer type
../../include/tds.h:656: note: expected ‘struct TDSSOCKET *’ but argument is of type ‘struct TDSLOGIN *’
tsql.c:267: warning: passing argument 2 of ‘tds_connect’ from incompatible pointer type
../../include/tds.h:656: note: expected ‘struct TDSLOGIN *’ but argument is of type ‘struct TDSCONTEXT *’
tsql.c:267: error: too many arguments to function ‘tds_connect’
tsql.c:267: warning: assignment makes pointer from integer without a cast
```

**Comment by freddy77** [comment] 2015-12-16 12:19
try www.freetds.org/freetds-0.100.dev.20151216.tar.bz2 (md5 2b5d7b26d08dc17256010d2d766ef13f).

**Comment by misterion** [comment] 2015-12-16 12:28
Yes, with this version connection time ~2,6ms - 3,5 ms and request time ~3,1 ms. Looks like a win :)

**Comment by freddy77** [comment] 2015-12-16 16:50
Thanks, is not pushed as these patches flush data too much causing more physical network packets than expected. I didn't analysed how much more packets are sent.

**Comment by misterion** [comment] 2015-12-17 07:38
I'll wait until the push. Then I check again. In the meantime, check for any leaks under high load on the pool.

**Comment by freddy77** [comment] 2015-12-24 12:32
Improved and merged.

**Closed by freddy77** 2015-12-24 12:32 UTC
