### ISSUE TITLE
freebcp - an option to escape \n with \\n and \t with \\t

### ISSUE THREAD

**Issue by zelid** [FreeTDS/freetds#103] opened 2017-03-01 11:43 UTC
When exporting huge (~500 GB) table that has rows containing \r\n, \n, \t is it possible to replace them with escaped \\n and \\t?
If not, how to change the code of freebcp to make this escape during the export?

Right now I do:
`freebcp MyDb.dbo.MailLogs out MailLogs.txt -c -k -S db3 -r "~!~!~!~" -t "@!@!@!@" -T`
Then:
```
perl -i.bak -p -e 's/\n/\\n/' MailLogs.txt
perl -i.bak -p -e 's/\t/\\t/' MailLogs.txt
perl -i.bak -p -e 's/~!~!~!~/\n/' MailLogs.txt
perl -i.bak -p -e 's/@!@!@!@/\t/' MailLogs.txt
```
And it would be very helpful to hack BCP source code to do the replacements together with export.

**Comment by freddy77** [comment] 2017-03-10 21:07
Have you tried the native format?
Note that you can escape strings passed with -r or -t creating difficult terminators (even not text)
If the problem is the temporary file you can try using a fifos (see man mkfifo). FreeTDS 1.0 should be able to cope with different file descriptors. If you are on Linux you could use some virtual file like "/proc/self/fd/3" and redirecting file descriptor 3 (for instance) to perl.

**Comment by freddy77** [comment] 2017-08-01 12:51
Closing, no reply since March.

**Closed by freddy77** 2017-08-01 12:51 UTC
